# Site settings
title: NovoSee
subtitle: 
email: vivid.novosee@gmail.com
description: vivid
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Joe PENG
street_address: 
city: Sydney
state: NSW
zip_code: 2000
country: Australia
phone: 

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: aaa 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
